version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    depends_on:
      - mongo
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://mongo:27017/meteor
      PORT: 3000
      ENVNAME: 'LocalServer'
      POSTGRES_DB_HOST: 'host.docker.internal'
      POSTGRES_DB_NAME: 'ipcdb_dev'
      POSTGRES_DB_PORT: '5432'
      POSTGRES_DB_USER: 'ipc_vps'
      POSTGRES_DB_PASSWORD: 'SetAPasswordHere'
  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db

volumes:
  data:
