version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    depends_on:
      - mongo
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://mongo:27017/meteor
      PORT: 3000
      METEOR_SETTINGS: '{"public":{"environmentName":"LocalServer","postgresInfo":{"host":"host.docker.internal","database":"ipcdb_dev","port":5432}},"private":{"postgres":{"user":"ipc_vps","password":"SomePassword"},"MAIL_URL":""}}'

  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db

volumes:
  data:
