FROM centos:7

LABEL Christian Kurmann <cku@tere.tech>

RUN groupadd -r node && useradd -m -g node node

# GOSU Version
ENV GOSU_VERSION 1.11

# build directories
ENV APP_SOURCE_DIR /opt/meteor/src
ENV APP_BUNDLE_DIR /opt/meteor/dist
ENV BUILD_SCRIPTS_DIR /opt/build_scripts

# Add entrypoint and build scripts
COPY scripts $BUILD_SCRIPTS_DIR
RUN chmod -R 750 $BUILD_SCRIPTS_DIR

# Define all --build-arg options
ONBUILD ARG YUM_INSTALL
ONBUILD ENV YUM_INSTALL $YUM_INSTALL

ONBUILD ARG NPM_TOKEN
ONBUILD ENV NPM_TOKEN $NPM_TOKEN

ONBUILD ARG INSTALL_MONGO
ONBUILD ENV INSTALL_MONGO $INSTALL_MONGO

# Node flags for the Meteor build tool
ONBUILD ARG TOOL_NODE_FLAGS
ONBUILD ENV TOOL_NODE_FLAGS $TOOL_NODE_FLAGS

# optionally custom apt dependencies at app build time
# ONBUILD RUN if [ "$YUM_INSTALL" ]; then yum update -y && yum install -y $YUM_INSTALL; fi

# copy the app to the container
ONBUILD COPY . $APP_SOURCE_DIR

# install all dependencies, build app, clean up
ONBUILD RUN cd $APP_SOURCE_DIR
ONBUILD RUN $BUILD_SCRIPTS_DIR/install-deps.sh
ONBUILD RUN $BUILD_SCRIPTS_DIR/install-node.sh
ONBUILD RUN $BUILD_SCRIPTS_DIR/install-passenger.sh
ONBUILD RUN $BUILD_SCRIPTS_DIR/install-mongo.sh
ONBUILD RUN $BUILD_SCRIPTS_DIR/install-meteor.sh
ONBUILD RUN $BUILD_SCRIPTS_DIR/build-meteor.sh
ONBUILD RUN $BUILD_SCRIPTS_DIR/post-build-cleanup.sh

# Default values for Meteor environment variables
ENV ROOT_URL http://localhost
ENV MONGO_URL mongodb://127.0.0.1:27017/meteor
ENV PORT 3000

EXPOSE 3000

WORKDIR $APP_BUNDLE_DIR/bundle

# start the app
ENTRYPOINT ["./entrypoint.sh"]